### PR TITLE
declare dependencies

### PR DESCRIPTION
**Pull request by rgolangh**
- Fix README typos and rename rgolangh to parodos.dev
- Add dependencies to the root Chart.yaml

### CODE REVIEW

**Comment by masayag** [comment]
@rgolangh No need to create a releaser for this repo?

**Comment by rgolangh** [comment]
> @rgolangh No need to create a releaser for this repo?

it does release -   for example https://github.com/parodos-dev/serverless-workflows-helm/actions/runs/7657605985/job/20868690762

**Comment by masayag** [comment]
> > @rgolangh No need to create a releaser for this repo?
> 
> it does release - for example https://github.com/parodos-dev/serverless-workflows-helm/actions/runs/7657605985/job/20868690762

Don't know how I missed it :-)

**Review by masayag — APPROVED** [review]

**Comment by rgolangh** [comment]
> Don't know how I missed it :-)

that's because it's not showing up in the pull request page maybe?

**Pull request merged**
